export const users = [
  {
    first_name: "Vyyyyy",
    last_name: "thích dạo menu",
    email: "lanvy.ielts1984@gmail.com",
    password: null,
    avatar: "5ed19e95-3d84-4a26-a76e-e4aff58faf7d",
  },
  {
    first_name: "Hòa",
    last_name: "Phan đang kiêng trà sữa",
    avatar: "d90743ee-25d1-43ac-a28e-28cef58d08da",
  },

  {
    first_name: "Tí",
    last_name: "pha nỳ",
    avatar: "50d1307c-8422-4753-bec1-8e0f3f8130f9",
  },

  {
    first_name: "Thanh",
    last_name: "Ngân Võ",
    company: 3,
    email: "thanhngan170801@gmail.com",
    avatar: "2a8f6b10-e8db-458f-9b13-439887b6c2d8",
  },
  {
    first_name: "Truong",
    last_name: "HQ",
    company: 3,
    email: "huynhquoctruongit@gmail.com",
    password: null,
    avatar: "ab8fe021-3398-41e8-aca6-542fd5cddf8c",
    location: null,
    title: null,
    description: null,
    tags: null,
    language: null,
    tfa_secret: null,
    appearance: null,
    theme_light: null,
    theme_dark: null,
    status: "active",
    role: "c3fa70d9-daa4-4964-9f3c-50397109ecfe",
    id: "aff00924-4822-4585-a0e3-e62ca8d79cfa",
    provider: "google",
    last_page: null,
    qr_code_for_payment: null,
    permission_to_update_order: true,
    permission_to_create_menu: true,
  },
  {
    first_name: "Tân",
    last_name: "",
    company: 3,
    email: "academic@ielts1984.edu.vn",
    password: null,
    avatar: "2f961a8c-0674-4867-8233-16dc3cc98dd4",
    location: null,
    title: null,
    description: null,
    tags: null,
    language: null,
    tfa_secret: null,
    appearance: null,
    theme_light: null,
    theme_dark: null,
    status: "active",
    role: "c3fa70d9-daa4-4964-9f3c-50397109ecfe",
    id: "b8535c4f-7a81-495d-894e-2bdef55005c9",
    provider: "google",
    last_page: null,
    qr_code_for_payment: null,
    permission_to_update_order: null,
    permission_to_create_menu: null,
  },

  {
    first_name: "Bé",
    last_name: "Linh",
    company: 3,
    email: "linhlyd149@gmail.com",
    password: null,
    avatar: "1f4bb4e1-dc5b-4462-ab98-d2441faad2b1",
    location: null,
    title: null,
    description: null,
    tags: null,
    language: null,
    tfa_secret: null,
    appearance: null,
    theme_light: null,
    theme_dark: null,
    status: "active",
    role: "c3fa70d9-daa4-4964-9f3c-50397109ecfe",
    id: "befcfba9-b0c7-469c-9094-2e48c7f68072",
    provider: "google",
    last_page: null,
    qr_code_for_payment: null,
    permission_to_update_order: null,
    permission_to_create_menu: null,
  },
  {
    first_name: "Trưởng",
    last_name: "Huỳnh",
    company: 3,
    email: "huynhquoctruongit2@gmail.com",
    password: "**********",
    avatar: "ab8fe021-3398-41e8-aca6-542fd5cddf8c",
    location: null,
    title: null,
    description: null,
    tags: null,
    language: null,
    tfa_secret: null,
    appearance: null,
    theme_light: null,
    theme_dark: null,
    status: "active",
    role: "17717844-cb1c-43cf-aa5d-0210509d5f58",
    id: "c1a44082-d373-4dbf-8718-8574a10d2292",
    provider: "default",
    last_page: "/content/order/748",
    qr_code_for_payment: null,
    permission_to_update_order: null,
    permission_to_create_menu: null,
  },
  {
    first_name: "Trịnh",
    last_name: "Trần Khánh Linh",
    company: 3,
    email: "khanhlinh05nt.edu@gmail.com",
    password: null,
    avatar: "3ecb7fd0-2502-4e22-9241-964aa7656d30",
    location: null,
    title: null,
    description: null,
    tags: null,
    language: null,
    tfa_secret: null,
    appearance: null,
    theme_light: null,
    theme_dark: null,
    status: "active",
    role: "c3fa70d9-daa4-4964-9f3c-50397109ecfe",
    id: "cf24ee64-45dd-4744-9402-097df91f261c",
    provider: "google",
    last_page: null,
    qr_code_for_payment: null,
    permission_to_update_order: null,
    permission_to_create_menu: null,
  },
  {
    first_name: "Truong",
    last_name: "Kuang",
    company: 3,
    email: "kuangtruong@gmail.com",
    password: null,
    avatar: "d26444c0-d075-4270-a432-45561ebaee85",
    location: null,
    title: null,
    description: null,
    tags: null,
    language: null,
    tfa_secret: null,
    appearance: null,
    theme_light: null,
    theme_dark: null,
    status: "active",
    role: "c3fa70d9-daa4-4964-9f3c-50397109ecfe",
    id: "e37c9923-90d4-435c-bb97-f46ba0f82f85",
    provider: "google",
    last_page: null,
    qr_code_for_payment: null,
    permission_to_update_order: null,
    permission_to_create_menu: null,
  },
  {
    first_name: "Chị",
    last_name: "Linh xinh lung linh",
    company: 3,
    email: "linhphan.vn@gmail.com",
    password: null,
    avatar: "adee1a97-199a-4ba5-9a67-573626bc0f7c",
    location: null,
    title: null,
    description: null,
    tags: null,
    language: null,
    tfa_secret: null,
    appearance: null,
    theme_light: null,
    theme_dark: null,
    status: "active",
    role: "c3fa70d9-daa4-4964-9f3c-50397109ecfe",
    id: "e795e94b-bbde-4733-a58e-9e671a2320fb",
    provider: "google",
    last_page: null,
    qr_code_for_payment: null,
    permission_to_update_order: null,
    permission_to_create_menu: null,
  },
  {
    first_name: "bé",
    last_name: "Đức",
    company: 3,
    email: "ducnguyen08091999@gmail.com",
    password: null,
    avatar: "f63e750d-2b50-44c1-813a-6940cab4c43f",
    location: null,
    title: null,
    description: null,
    tags: null,
    language: null,
    tfa_secret: null,
    appearance: null,
    theme_light: null,
    theme_dark: null,
    status: "active",
    role: "c3fa70d9-daa4-4964-9f3c-50397109ecfe",
    id: "e8408863-2e54-4043-9ca3-db91491ea6bb",
    provider: "google",
    last_page: null,
    qr_code_for_payment: null,
    permission_to_update_order: null,
    permission_to_create_menu: null,
  },

  {
    first_name: "Quang",
    last_name: "Trương",
    company: 3,
    email: "truongdangquang1511@gmail.com",
    password: null,
    avatar: "d26444c0-d075-4270-a432-45561ebaee85",
    location: null,
    title: null,
    description: null,
    tags: null,
    language: null,
    tfa_secret: null,
    appearance: null,
    theme_light: null,
    theme_dark: null,
    status: "active",
    role: "c3fa70d9-daa4-4964-9f3c-50397109ecfe",
    id: "fc8233d0-08b6-4000-9e11-9a5699d3d204",
    provider: "google",
    last_page: null,
    qr_code_for_payment: null,
    permission_to_update_order: null,
    permission_to_create_menu: null,
  },
  {
    first_name: "Vũ",
    last_name: "",
    company: 3,
    email: "leeanhvux2111@gmail.com",
    password: null,
    avatar: "3ecb7fd0-2502-4e22-9241-964aa7656d30",
    location: null,
    title: null,
    description: null,
    tags: null,
    language: null,
    tfa_secret: null,
    appearance: null,
    theme_light: null,
    theme_dark: null,
    status: "active",
    role: "c3fa70d9-daa4-4964-9f3c-50397109ecfe",
    id: "fe081a38-3b35-4c7e-8de1-d30a94e0800b",
    provider: "google",
    last_page: null,
    qr_code_for_payment: null,
    permission_to_update_order: null,
    permission_to_create_menu: null,
  },
];

export const orders = [
  {
    id: 1005,
    status: "published",
    sort: null,
    date_created: "2024-09-26T03:08:12.325Z",
    user_updated: null,
    date_updated: null,
    company: 3,
    bulk_food_provider: 1,
    is_paid: false,
    confirm_paid: false,
    name: "Xíu mại xốt cà chua",
    note: "",
    delivery_fee: null,
    price_fee: null,
    price: 35,
    paid_user: null,
    date_order: null,
    user_created: {
      first_name: "Bé",
      last_name: "Linh",
      company: 3,
      email: "linhlyd149@gmail.com",
      password: null,
      avatar: "1f4bb4e1-dc5b-4462-ab98-d2441faad2b1",
      location: null,
      title: null,
      description: null,
      tags: null,
      language: null,
      tfa_secret: null,
      appearance: null,
      theme_light: null,
      theme_dark: null,
      status: "active",
      role: "c3fa70d9-daa4-4964-9f3c-50397109ecfe",
      id: "befcfba9-b0c7-469c-9094-2e48c7f68072",
      provider: "google",
      last_page: null,
      qr_code_for_payment: null,
      permission_to_update_order: null,
      permission_to_create_menu: null,
    },
  },
  {
    id: 1007,
    status: "published",
    sort: null,
    date_created: "2024-09-26T03:08:32.777Z",
    user_updated: null,
    date_updated: null,
    company: 3,
    bulk_food_provider: 1,
    is_paid: false,
    confirm_paid: false,
    name: "Xíu mại xốt cà chua",
    note: "mix trứng",
    delivery_fee: null,
    price_fee: null,
    price: 35,
    paid_user: null,
    date_order: null,
    user_created: {
      first_name: "Nhất",
      last_name: "Code Lỏ",
      company: 3,
      email: "nhatnn1808@gmail.com",
      password: null,
      avatar: "cbbdbbbe-9337-4529-84f0-2584a298a4f1",
      location: null,
      title: null,
      description: null,
      tags: null,
      language: null,
      tfa_secret: null,
      appearance: null,
      theme_light: null,
      theme_dark: null,
      status: "active",
      role: "c3fa70d9-daa4-4964-9f3c-50397109ecfe",
      id: "8e355e55-72cb-497f-b821-09110a5fc537",
      provider: "google",
      last_page: null,
      qr_code_for_payment: null,
      permission_to_update_order: true,
      permission_to_create_menu: true,
    },
  },
  {
    id: 1008,
    status: "published",
    sort: null,
    date_created: "2024-09-26T03:08:51.993Z",
    user_updated: null,
    date_updated: null,
    company: 3,
    bulk_food_provider: 1,
    is_paid: false,
    confirm_paid: false,
    name: "Thịt xào măng",
    note: "",
    delivery_fee: null,
    price_fee: null,
    price: 35,
    paid_user: null,
    date_order: null,
    user_created: {
      first_name: "Thanh",
      last_name: "Ngân Võ",
      company: 3,
      email: "thanhngan170801@gmail.com",
      password: null,
      avatar: "2a8f6b10-e8db-458f-9b13-439887b6c2d8",
      location: null,
      title: null,
      description: null,
      tags: null,
      language: null,
      tfa_secret: null,
      appearance: null,
      theme_light: null,
      theme_dark: null,
      status: "active",
      role: "c3fa70d9-daa4-4964-9f3c-50397109ecfe",
      id: "6db80555-a0d1-4186-840b-2a15bf1b1738",
      provider: "google",
      last_page: null,
      qr_code_for_payment: null,
      permission_to_update_order: null,
      permission_to_create_menu: null,
    },
  },

  {
    id: 1011,
    status: "published",
    sort: null,
    date_created: "2024-09-26T03:10:41.641Z",
    user_updated: null,
    date_updated: null,
    company: 3,
    bulk_food_provider: 1,
    is_paid: false,
    confirm_paid: false,
    name: "Xíu mại xốt cà chua",
    note: "",
    delivery_fee: null,
    price_fee: null,
    price: 35,
    paid_user: null,
    date_order: null,
    user_created: {
      first_name: "Dinh",
      last_name: "Minh",
      company: 3,
      email: "dinhtuanminh0612@gmail.com",
      password: null,
      avatar: "40d5651a-b877-4c7a-97c3-f9c0bead838e",
      location: null,
      title: null,
      description: null,
      tags: null,
      language: null,
      tfa_secret: null,
      appearance: null,
      theme_light: null,
      theme_dark: null,
      status: "active",
      role: "c3fa70d9-daa4-4964-9f3c-50397109ecfe",
      id: "59504d0d-67b7-4b65-a258-c471b8aa6b7b",
      provider: "google",
      last_page: null,
      qr_code_for_payment: null,
      permission_to_update_order: null,
      permission_to_create_menu: null,
    },
  },
  {
    id: 1012,
    status: "published",
    sort: null,
    date_created: "2024-09-26T03:12:41.436Z",
    user_updated: null,
    date_updated: null,
    company: 3,
    bulk_food_provider: 1,
    is_paid: false,
    confirm_paid: false,
    name: "Xíu mại xốt cà chua",
    note: "",
    delivery_fee: null,
    price_fee: null,
    price: 35,
    paid_user: null,
    date_order: null,
    user_created: {
      first_name: "Truong",
      last_name: "HQ",
      company: 3,
      email: "huynhquoctruongit@gmail.com",
      password: null,
      avatar: "ab8fe021-3398-41e8-aca6-542fd5cddf8c",
      location: null,
      title: null,
      description: null,
      tags: null,
      language: null,
      tfa_secret: null,
      appearance: null,
      theme_light: null,
      theme_dark: null,
      status: "active",
      role: "c3fa70d9-daa4-4964-9f3c-50397109ecfe",
      id: "aff00924-4822-4585-a0e3-e62ca8d79cfa",
      provider: "google",
      last_page: null,
      qr_code_for_payment: null,
      permission_to_update_order: true,
      permission_to_create_menu: true,
    },
  },
  {
    id: 1013,
    status: "published",
    sort: null,
    date_created: "2024-09-26T03:13:13.603Z",
    user_updated: null,
    date_updated: null,
    company: 3,
    bulk_food_provider: 1,
    is_paid: false,
    confirm_paid: false,
    name: "Thịt xào măng",
    note: "",
    delivery_fee: null,
    price_fee: null,
    price: 35,
    paid_user: null,
    date_order: null,
    user_created: {
      first_name: "Tí",
      last_name: "pha nỳ",
      company: 3,
      email: "tribui170901@gmail.com",
      password: null,
      avatar: "50d1307c-8422-4753-bec1-8e0f3f8130f9",
      location: null,
      title: null,
      description: null,
      tags: null,
      language: null,
      tfa_secret: null,
      appearance: null,
      theme_light: null,
      theme_dark: null,
      status: "active",
      role: "c3fa70d9-daa4-4964-9f3c-50397109ecfe",
      id: "5f5c5a3e-7bdd-452c-997a-955bd4af03f5",
      provider: "google",
      last_page: null,
      qr_code_for_payment: null,
      permission_to_update_order: null,
      permission_to_create_menu: null,
    },
  },
  {
    id: 1014,
    status: "published",
    sort: null,
    date_created: "2024-09-26T03:13:34.463Z",
    user_updated: null,
    date_updated: null,
    company: 3,
    bulk_food_provider: 1,
    is_paid: false,
    confirm_paid: false,
    name: "Cá hú kho tiêu",
    note: "",
    delivery_fee: null,
    price_fee: null,
    price: 35,
    paid_user: null,
    date_order: null,
    user_created: {
      first_name: "bé",
      last_name: "Đức",
      company: 3,
      email: "ducnguyen08091999@gmail.com",
      password: null,
      avatar: "f63e750d-2b50-44c1-813a-6940cab4c43f",
      location: null,
      title: null,
      description: null,
      tags: null,
      language: null,
      tfa_secret: null,
      appearance: null,
      theme_light: null,
      theme_dark: null,
      status: "active",
      role: "c3fa70d9-daa4-4964-9f3c-50397109ecfe",
      id: "e8408863-2e54-4043-9ca3-db91491ea6bb",
      provider: "google",
      last_page: null,
      qr_code_for_payment: null,
      permission_to_update_order: null,
      permission_to_create_menu: null,
    },
  },
  {
    id: 1019,
    status: "published",
    sort: null,
    date_created: "2024-09-26T03:27:21.718Z",
    user_updated: null,
    date_updated: null,
    company: 3,
    bulk_food_provider: 1,
    is_paid: false,
    confirm_paid: false,
    name: "Gà kho xả ớt",
    note: "",
    delivery_fee: null,
    price_fee: null,
    price: 35,
    paid_user: null,
    date_order: null,
    user_created: {
      first_name: "Trinh",
      last_name: "Lê",
      company: 3,
      email: "thaotrinh.le2811@gmail.com",
      password: null,
      avatar: "c7099f8d-f895-443f-9b08-98902bf8b92f",
      location: null,
      title: null,
      description: null,
      tags: null,
      language: null,
      tfa_secret: null,
      appearance: null,
      theme_light: null,
      theme_dark: null,
      status: "active",
      role: "c3fa70d9-daa4-4964-9f3c-50397109ecfe",
      id: "04ea3af9-c271-475b-97bc-586e873e5f8b",
      provider: "google",
      last_page: null,
      qr_code_for_payment: null,
      permission_to_update_order: null,
      permission_to_create_menu: null,
    },
  },

  {
    id: 1021,
    status: "published",
    sort: null,
    date_created: "2024-09-26T03:42:58.869Z",
    user_updated: null,
    date_updated: null,
    company: 3,
    bulk_food_provider: 1,
    is_paid: false,
    confirm_paid: false,
    name: "Xíu mại xốt cà chua",
    note: "",
    delivery_fee: null,
    price_fee: null,
    price: 25,
    paid_user: null,
    date_order: null,
    user_created: {
      first_name: "Tân",
      last_name: "",
      company: 3,
      email: "academic@ielts1984.edu.vn",
      password: null,
      avatar: "2f961a8c-0674-4867-8233-16dc3cc98dd4",
      location: null,
      title: null,
      description: null,
      tags: null,
      language: null,
      tfa_secret: null,
      appearance: null,
      theme_light: null,
      theme_dark: null,
      status: "active",
      role: "c3fa70d9-daa4-4964-9f3c-50397109ecfe",
      id: "b8535c4f-7a81-495d-894e-2bdef55005c9",
      provider: "google",
      last_page: null,
      qr_code_for_payment: null,
      permission_to_update_order: null,
      permission_to_create_menu: null,
    },
  },
  {
    id: 1022,
    status: "published",
    sort: null,
    date_created: "2024-09-26T03:43:01.786Z",
    user_updated: null,
    date_updated: null,
    company: 3,
    bulk_food_provider: 1,
    is_paid: false,
    confirm_paid: false,
    name: "Cá hú kho tiêu",
    note: "",
    delivery_fee: null,
    price_fee: null,
    price: 35,
    paid_user: null,
    date_order: null,
    user_created: {
      first_name: "Tân",
      last_name: "",
      company: 3,
      email: "academic@ielts1984.edu.vn",
      password: null,
      avatar: "2f961a8c-0674-4867-8233-16dc3cc98dd4",
      location: null,
      title: null,
      description: null,
      tags: null,
      language: null,
      tfa_secret: null,
      appearance: null,
      theme_light: null,
      theme_dark: null,
      status: "active",
      role: "c3fa70d9-daa4-4964-9f3c-50397109ecfe",
      id: "b8535c4f-7a81-495d-894e-2bdef55005c9",
      provider: "google",
      last_page: null,
      qr_code_for_payment: null,
      permission_to_update_order: null,
      permission_to_create_menu: null,
    },
  },
];

export const chartsData = [
  {
    date_created_week: "34",
    sum: {
      price: "35",
      delivery_fee: null,
    },
  },
  {
    date_created_week: "35",
    sum: {
      price: "140",
      delivery_fee: null,
    },
  },
  {
    date_created_week: "36",
    sum: {
      price: "70",
      delivery_fee: null,
    },
  },
  {
    date_created_week: "37",
    sum: {
      price: "140",
      delivery_fee: null,
    },
  },
  {
    date_created_week: "38",
    sum: {
      price: "140",
      delivery_fee: null,
    },
  },
  {
    date_created_week: "39",
    sum: {
      price: "105",
      delivery_fee: null,
    },
  },
];
